### ISSUE TITLE
SQL Server 2017: Create database outside transaction

### ISSUE THREAD

**Issue by lunderhage** [lecaillon/Evolve#186]
I am trying to create a database in SQL Server 2017 after have reading this PR:

https://github.com/lecaillon/Evolve/pull/150/files

```
-- evolve-tx-off
CREATE DATABASE people_registry;

```
Database is created, but:
```
Executing Migrate...
Evolve initialized.
No metadata found.
Successfully applied migration V1__create_db.sql in 1093 ms.
Cannot release the application lock (Database Principal: 'public', Resource: 'Evolve') because it is not currently held. Sql query: sp_releaseapplock Cannot release the application lock (Database Principal: 'public', Resource: 'Evolve') because it is not currently held.
Cannot release the application lock (Database Principal: 'public', Resource: 'Evolve') because it is not currently held. Sql query: sp_releaseapplock Cannot release the application lock (Database Principal: 'public', Resource: 'Evolve') because it is not currently held.
```

Why does Evolve think it has the lock here and why does it fail because it did not? I appreciate some guidance here.

**Comment by lecaillon** [comment]
Hi,
I'm surprised by this behavior because I have a test [here ](Run_all_SQLServer_migrations_work)that uses this [migration](https://github.com/lecaillon/Evolve/blob/master/test/Evolve.Tests/Integration/SQLServer/Resources/Sql_Scripts/Migration/V3_1__create_database_evolvedb.sql).
``` sql
-- evolve-tx-off
IF(db_id(N'evolvedb') IS NOT NULL)
BEGIN
	DROP DATABASE evolvedb;
END;

CREATE DATABASE evolvedb;
```
Is this the only statement you have in the migration file ?
Maybe you can give me more insight about the context of your migration : os, database etc ?

**Comment by lunderhage** [comment]
Yes, that is the only sql script I have in Sql_Scripts. I am just trying to create a new database from scratch. I want to make a demo for my colleague with some different databases. CockroachDB was dead easy.

SQL Server (Linux) is:
```
version: "3.4"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1T2e3S4t
    ports:
      - 1433:1433
    volumes:
      - sql-server-data:/var/opt/mssql
volumes:
  sql-server-data:
```
